services:
  server:
    container_name: server
    build:
      context: ./poefree-server
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://jaycebordelon:1234@postgres:5432/poefree_db
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./poefree-server:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: jaycebordelon
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: poefree_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  client:
    container_name: client
    build:
      context: ./poefree-client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./poefree-client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

volumes:
  postgres_data:
